export const Permissions = {
    "view_tickets": "Ver multas",
    "create_tickets": "Crear multas",
    "edit_tickets": "Editar multas",
    "create_claim": "Crear reclamos",
    "view_claims": "Ver reclamos",
    "respond_claims": "Responder reclamos",
    "view_users": "Ver usuarios",
    "create_users": "Crear usuarios",
    "edit_users": "Editar usuarios",
    "delete_users": "Eliminar usuarios",
    "view_roles": "Ver roles",
    "create_roles": "Crear roles",
    "edit_roles": "Editar roles",
    "delete_roles": "Eliminar roles",
    "create_declaration": "Crear declaración",
    "view_declaration": "Ver declaración",
    "create_ticket_from_image": "Crear multa desde imagen",
    "do_payment": "Realizar pago",
    "view_payments": "Ver pagos",
    "view_reports": "Ver informes",
    "create_reports": "Crear informes",
    "view_profile": "Ver perfil",
    "edit_profile": "Editar perfil",
}