export const Permissions = {
    "view_tickets": "view_tickets",
    "create_tickets": "create_tickets",
    "edit_tickets": "edit_tickets",
    "create_claim": "create_claim",
    "view_claims": "view_claims",
    "respond_claims": "respond_claims",
    "view_users": "view_users",
    "create_users": "create_users",
    "edit_users": "edit_users",
    "delete_users": "delete_users",
    "view_roles": "view_roles",
    "create_roles": "create_roles",
    "edit_roles": "edit_roles",
    "delete_roles": "delete_roles",
    "create_declaration": "create_declaration",
    "view_declaration": "view_declaration",
    "create_ticket_from_image": "create_ticket_from_image",
    "do_payment": "do_payment",
    "view_payments": "view_payments",
    "view_reports": "view_reports",
    "create_reports": "create_reports",
    "view_profile": "view_profile",
    "edit_profile": "edit_profile",
    "plate_detection": "plate_detection",
}